SiliconLabsSoftware/matter_sdk

examples/platform/silabs/MatterConfig.cpp
Added the line to disable the em1 req from OT
=> [SL-TEMP] Bugfix temporary em req removal

.github/CODEOWNERS
PR adds the silabs codeowner file for the Matter v1.4 release branch
=> [SL-TEMP] Add codeowners file to the release branch

examples/thermostat/silabs/include/SensorManager.h, examples/thermostat/silabs/src/SensorManager.cpp
This PR cherry-picks the changes from CSA master PR : [#35721](https://github.com/project-chip/connectedhomeip/pull/35721)
=> [CSA-CP] Fix thermostat hang issue for SOC.

examples/platform/silabs/provision/ProvisionStorageDefault.cpp
CSA Cherry Pick https://github.com/project-chip/connectedhomeip/pull/36250#issue-2614804073  for test event trigger slc support.
=> [CSA-CP] Test event trigger slc support

examples/lock-app/silabs/data_model/lock-app.matter, examples/lock-app/silabs/data_model/lock-app.zap
We currently do not support Aliro in our doorlock app so the Alio features were removes from the doorlock cluster feature map.
=> [SL-UP] Doorlock featuremap Aliro Removal

scripts/tools/silabs/retrieve_sl_commits.py
Cherry pick from PR #83 
+ add the Autor to the git log output
=> [SL-ONLY] First version of the script to parse git branches for our commits TAG

examples/platform/silabs/MatterShell.cpp
MATTER-4371
Cherry-pick of https://github.com/project-chip/connectedhomeip/pull/36583 to matter_sdk
=> [CSA-CP] use VerifyOrDie instead of assert() (#36583)

examples/platform/silabs/MatterConfig.cpp
Removed a trace that was left behind during integration.
=> [SL-ONLY]Bugfix/wrong boot end trace

src/platform/silabs/efr32/CHIPCryptoPALPsaEfr32.cpp
Fixes: DAC sign error with default certificates.
Tested on BRD4187C.
=> Default Crypto PAL PSA copied into EFR32 with optimizations.

examples/platform/silabs/provision/ProvisionStorageFlash.cpp, src/platform/silabs/platformAbstraction/WiseMcuSpam.cpp, src/platform/silabs/provision/AttestationKey.h, src/platform/silabs/provision/ProvisionManager.h, src/platform/silabs/provision/ProvisionProtocol.h, src/platform/silabs/provision/ProvisionStorage.h
- Adds changes to Provision Storage flash to save private key into storage
- Adds changes to use pointer to execute Provision APIs
=> [SL-UP] Adds changes for generator firmware

.github/silabs-builds-mg24.json, .github/silabs-builds-mg26.json, .github/silabs-builds-mgm24.json, .github/silabs-builds-siwx.json, .github/workflows/silabs-build-examples.yaml, .github/workflows/silabs-common-build.yaml, examples/air-quality-sensor-app/silabs/build_for_wifi_gnfile.gn, examples/lit-icd-app/silabs/build_for_wifi_gnfile.gn, examples/pump-app/silabs/build_for_wifi_gnfile.gn, examples/smoke-co-alarm-app/silabs/build_for_wifi_gnfile.gn, src/platform/silabs/wifi/rs911x/rs9117.gni
Cherry-Pick of [#178](https://github.com/SiliconLabsSoftware/matter_sdk/pull/178). Marking as SL-TEMP since the PR will introduce build fixes that are not necessary for main or csa.
CI
=> [SL-TEMP] Add custom silabs worklfows to build sample apps (#178)

.github/workflows/silabs-require-admin-action-check.yaml
The initial action was using a mismatch of gh commands and github action which made it pretty complexe to understand and maintan.
Updating the action to use javascript in the action to execute the necessary steps which makes this much cleaner.
=> [SL-ONLY] Simplify require admin workflow

src/platform/silabs/efr32/CHIPCryptoPALPsaEfr32.cpp
* [Cherry-pick from CSA](https://github.com/project-chip/connectedhomeip/pull/37580)
* Fixes #[35155](https://github.com/project-chip/connectedhomeip/issues/35155) in Silicon Labs devices.
* Tested on BRD4187C (MG24) and BRD4118A (MG26).
=> [CSA-CP] Bugfix: PSA AEAD encryption.

.github/workflows/silabs-common-build.yaml
=> [SL-ONLY] Bump docker image to use updated skds

examples/fan-control-app/silabs/data_model/fan-control-thread-app.matter, examples/fan-control-app/silabs/data_model/fan-control-wifi-app.matter
Latest CSA update of main cause the zap generation CI to fail due to the fan control app.
PR regenerates both zap files.
CI
=> [SL-ONLY] Update Fan Control App zap generation

src/platform/silabs/wifi/icd/WifiSleepManager.cpp
The introduction of the WifiInterface changes the API signature for certain function. PR udpates silabs specific code to use the new interfaces.
Build CI to validate there a no failures
=> [SL-ONLY] Update LI configuration function to use the Wifi interface

.gitmodules
Point the matter_support submodule to release_2.6-1.4
CI
=> [SL-TEMP] Point the matter_support submodule to release_2.6-1.4

.github/CODEOWNERS
> !!!!!!!!!! Please delete the instructions below and replace with PR
> description above.
>
> If you have an issue number, please use a syntax of `Fixes #12345` and a brief
> change description
>
> If you do not have an issue number, please have a good description of the
> problem and the fix. Help the reviewer understand what to expect.
>
> Complete/append to the `### Testing` section above, to describe how testing
> was done. See
> <https://github.com/project-chip/connectedhomeip/blob/master/CONTRIBUTING.md#pull-requests>
>
> Make sure you delete these instructions (to prove you have read them).
>
> !!!!!!!!!! Instructions end
=> [SL-TEMP] Update CODEOWNERS

examples/platform/silabs/sensors/AirQuality/AirQualitySensor.cpp
Tested in simplicity studio with brd2704a and added the spakfun air quality sensor.
=> [CSA-CP] remove extern air quality

examples/fan-control-app/silabs/data_model/fan-control-thread-app.matter, examples/fan-control-app/silabs/data_model/fan-control-wifi-app.matter, examples/multi-sensor-app/silabs/data_model/multi-sensor-thread-app.matter, examples/multi-sensor-app/silabs/data_model/multi-sensor-wifi-app.matter, examples/onoff-plug-app/silabs/data_model/onoff-plug-app.matter, examples/template/silabs/template_DataModel_config/sl_template.matter
After CSA update, silabs specific app required a zap regen
CI
=> [SL-ONLY] Regenerate zap file for silabs specific sample apps

src/app/clusters/user-label-server/user-label-server.cpp, src/app/tests/suites/TestUserLabelClusterConstraints.yaml, src/platform/DeviceInfoProvider.cpp
* Enforce a maximum entry limit during append operations
* Add test for this change
No specific test done on my end.
CI validate everything builds. This has been on main for a while now.
=> [CSA-CP] User label max entry limit

src/inet/UDPEndPointImplOpenThread.cpp
Updated `OT_NETIF_THREAD` define to match changes in OT stack update.
Compile->Flash->Commission->Toggle
=> [SL-TEMP] OT_NETIF_THREAD_HOST

src/inet/UDPEndPointImplOpenThread.cpp
Built using matter_extension (with 2025 ifc2rc2) AND built with gn (using 2024 ...)
=> [SL-TEMP] bugfix/enum check udp endpoint

examples/platform/silabs/BaseApplication.cpp
Added the end trace for app init with the new app structure
Build and run zigbee-matter-light app
=> [SL-ONLY] Silabs Trace End BaseAppInit

examples/air-quality-sensor-app/silabs/include/AppEvent.h, examples/chef/silabs/include/AppEvent.h, examples/energy-management-app/silabs/include/AppEvent.h, examples/light-switch-app/silabs/include/AppEvent.h, examples/lighting-app/silabs/include/AppEvent.h, examples/lit-icd-app/silabs/include/AppEvent.h, examples/lock-app/silabs/include/AppEvent.h, examples/platform/silabs/BaseApplication.cpp, examples/platform/silabs/BaseApplication.h, examples/platform/silabs/display/lcd.h, examples/platform/silabs/provision/BUILD.gn, examples/platform/silabs/provision/ProvisionStorageFlash.cpp, examples/pump-app/silabs/include/AppEvent.h, examples/refrigerator-app/silabs/include/AppEvent.h, examples/smoke-co-alarm-app/silabs/include/AppEvent.h, examples/thermostat/silabs/include/AppEvent.h, examples/window-app/silabs/include/AppEvent.h, src/lwip/silabs/lwipopts-rs911x.h, src/lwip/silabs/lwipopts-wf200.h, src/platform/silabs/NetworkCommissioningWiFiDriver.cpp, src/platform/silabs/wifi/rs911x/rsi_wlan_config.h, third_party/silabs/silabs_board.gni
Merge of Release 2.5-1.4 into Release 2.6-1.4
**Should be fast-forward merge!**
CI to validate all builds.
Test commissioning on EFR32 Thread.
=> Merge Release 2.5-1.4 into Release 2.6-1.4

examples/light-switch-app/silabs/include/AppConfig.h, examples/light-switch-app/silabs/include/AppTask.h, examples/light-switch-app/silabs/include/LightSwitchMgr.h, examples/light-switch-app/silabs/src/AppTask.cpp, examples/light-switch-app/silabs/src/LightSwitchMgr.cpp
This is a cherry-pick PR from CSA to bring in the button handling changes for dimmer switch app.
Tested the button events manually on 917SOC board.
=> [CSA-CP] Button handling fix for dimmer-switch

examples/air-quality-sensor-app/silabs/include/AirQualityConfig.h, examples/platform/silabs/sensors/AirQuality/AirQualitySensor.cpp
Able to build the app in Simplicity Studio.
CSA PR: https://github.com/project-chip/connectedhomeip/pull/38368
=> [CSA-CP] : Air quality sparkfun 917soc matter sdk

examples/zigbee-matter-light/silabs/include/AppConfig.h, examples/zigbee-matter-light/silabs/include/LightingManager.h, examples/zigbee-matter-light/silabs/include/ZigbeeCallbacks.h, examples/zigbee-matter-light/silabs/src/AppTask.cpp, examples/zigbee-matter-light/silabs/src/LightingManager.cpp, examples/zigbee-matter-light/silabs/src/MatterDMCallbacks.cpp, examples/zigbee-matter-light/silabs/src/ZigbeeCallbacks.cpp
The zigbee app was updated on the release branch but not on the matter_sdk when the app location is moved. 
the following PRs are added
https://stash.silabs.com/projects/WMN_TOOLS/repos/matter_extension/commits/50b82aff63f7d3e9536f1a15ea72f22efcbd5512#examples/zigbee-matter-light/src/MatterDMCallbacks.cpp
https://stash.silabs.com/projects/WMN_TOOLS/repos/matter_extension/commits/40e365085b4677e5297ef8630e9794d4f3f3137f#examples/zigbee-matter-light/include/AppConfig.h
Tested the build locally
=> [SL-ONLY] Update the zigbee app to the release branch

.github/workflows/examples-efr32.yaml, .gitmodules, examples/platform/silabs/ldscripts/SiWx917-common.ld, examples/platform/silabs/matter-platform.slcp, third_party/silabs/SiWx917_sdk.gni, third_party/silabs/efr32_sdk.gni
* bump silabs sdks submodules
* WIP - Add gn support for new sdk versions. Bump docker image for ci
* Revert to using older linker file and tartup_common_RS1xxxx
* used merged matter_support sha
* Use new startup code for si917
* Bump matter_support with provision lib fix. Remove unused files
* Add missing include path for 917 ncp builds
---------
Build a few apps on each platform (MG24, MG26, SI917), CI will validate additional build configurations.
Commission the lighting app on those 3 platforms.
=> [CSA-CP][Silabs]Update to latest sdks (#38762)

.github/workflows/tests.yaml
Disable Linux REPL tests that are repeatedly failing due to GH environment issues
N/A
=> [CSA-CP]Temporary REPL disabling to unblock CI (#38820)

examples/platform/silabs/cmp/ZigbeeCallbacks.h
Missing header move for ZigbeeCallbacks.h
=> [SL-ONLY]Hotfix: Header was not added to commit

examples/platform/silabs/BaseApplication.cpp, examples/platform/silabs/efr32/BUILD.gn, examples/platform/silabs/shell/BUILD.gn, examples/platform/silabs/shell/ble/BLEShellCommands.cpp, examples/platform/silabs/shell/ble/BLEShellCommands.h, src/platform/silabs/BLEManagerImpl.h, src/platform/silabs/efr32/BLEChannel.h, src/platform/silabs/efr32/BLEChannelImpl.cpp, src/platform/silabs/efr32/BLEChannelImpl.h, src/platform/silabs/efr32/BLEManagerImpl.cpp, src/platform/silabs/efr32/BUILD.gn, src/platform/silabs/rs911x/BLEManagerImpl.cpp, third_party/silabs/efr32_sdk.gni
Cherry pick of commits to enable the BLE-Side Channel in main.
=> [SL-TEMP] Cp/ble side channel

examples/platform/silabs/MatterConfig.cpp, src/platform/silabs/ConfigurationManagerImpl.cpp, src/platform/silabs/SiWx917/BUILD.gn, src/platform/silabs/SiWx917/OTAImageProcessorImpl.cpp, src/platform/silabs/SilabsConfig.h, src/platform/silabs/efr32/BUILD.gn, src/platform/silabs/efr32/OTAImageProcessorImpl.cpp, src/platform/silabs/multi-ota/OTAMultiImageProcessorImpl.cpp, src/platform/silabs/platformAbstraction/BUILD.gn, src/platform/silabs/platformAbstraction/GsdkSpam.cpp, src/platform/silabs/platformAbstraction/SilabsPlatform.cpp, src/platform/silabs/platformAbstraction/SilabsPlatform.h, src/platform/silabs/platformAbstraction/WiseMcuSpam.cpp
Added config to store a boolean to inform the app if a successful OTA triggered the reset.
https://jira.silabs.com/browse/MATTER-5199
manually tested :
Under 917, efr32 and series 3, OTA the device with new firmware and read the boot-reason using chip-tool.
code readable:
-   [x] PR size is short
-   [x] Try to avoid "squashing" and "force-update" in commit history
-   [x] CI time didn't increase
See: [Pull Request …
=> [SL-UP] Boot reason update multi-platform

.github/dependabot.yml
I forgot to push a change on the branch before i merged the PR without realising it. This corrects my mistakes
=> [SL-ONLY] Remove main target from dependabot

examples/platform/silabs/matter_aws/matter_aws_interface/src/MatterAwsControl.cpp
In Matter-AWS code, there are a couple of build errors seen with thermostat app.
This PR fixes the build errors observed in AWS code.
N/A
Added matter_aws component to thermostat 917 app, commissioned and verified that the data is being published to AWS server and the app is working as expected.
code readable:
-   [x] PR size is short
-   [x] Try to avoid "squashing" and "force-update" in commit history
-   [x] CI time didn't …
=> [SL-ONLY] Fix thermostat build errors with AWS

.github/workflows/CLA-Assistant.yml
Exclude Dependabot from CLA
Exclude silabs-matter-ci-bot 
code readable:
-   [x] PR size is short
-   [x] Try to avoid "squashing" and "force-update" in commit history
-   [x] CI time didn't increase
See: [Pull Request Guidelines](https://project-chip.github.io/connectedhomeip-doc/contributing/pull_request_guidelines.html)
=> exclude dependabot
