.github/CODEOWNERS
To set default reviewers, you need a `*` add the start of the CODEOWNDERS file. When reading the documentation, that star was lost in all the comments `#` symbol.
=> [SL-ONLY] Fix codeowners typo

.github/CODEOWNERS
Instead of having a single reviewing team. I broke down the teams a nested teams.
matter-watt/reviewers and matter-wifi/reviewers. 
This will give us more flexibility when a futur update when we add the missing review rules.
=> [SL-ONLY] Improve codeowners teams logic

examples/platform/silabs/BaseApplication.cpp
Fixes [MATTER-4273](https://jira.silabs.com/browse/MATTER-4273)
Add a snippet of code that was missing from the older branch structure to handle the Zigbee network when matter commissioning completes.
_Using [sl-temp] tag in the release branch as I will cherry-pick to Main immediately_
=> [SL-TEMP]Add Matter+zigbee cmp logic On matter commissioning complete

src/platform/silabs/BLEManagerImpl.h
This PR fixes build errors for 917ncp when additional data advertisement is enabled. This should be upstreamed to CSA master.
#36189 - This PR in CSA master refactored the BLE code. The change that is being pushed in this PR is missing in the CSA PR.
The build error is not seen in CSA as additional data advertisement is disabled by default. But in SLC, the additional data advertisement component is included for 917ncp, so faced the build error.
=> [SL-UP] Resolve build error for 917NCP

examples/platform/silabs/SiWx917/SiWx917/sl_wlan_config.h, scripts/build/build/targets.py, scripts/build/builders/efr32.py, scripts/build/testdata/all_targets_linux_x64.txt, scripts/examples/gn_silabs_example.sh, third_party/silabs/silabs_board.gni
This PR cherry-picks the fix for wifi init failure for brd4343a. This change has been merged in CSA master(#36111)
https://github.com/project-chip/connectedhomeip/pull/36111
=> [CSA-CP] Modify region code for module boards(brd4343a)

examples/platform/silabs/uart.cpp
Build fails for thermostat-rs911x.slcp if the matter_shell component is excluded. To fix skip the OpenThread API call in uart.cpp in case of WiFi builds. 
Verified in a FULL CI build on the matter_extension repo.
=> [SL-UP] Skip the OpenThread API call for WiFi builds

examples/platform/silabs/provision/ProvisionStorageDefault.cpp, examples/platform/silabs/provision/ProvisionStorageFlash.cpp, src/platform/silabs/SilabsConfig.h, src/platform/silabs/provision/ProvisionStorage.h
The Latest Specification made it clear that the Unique ID used for the rotation Device ID and the UniqueID attribute from the basic information cluster are not the same.
Our previously provisioned UniqueID remains untouched but it is now renamed PersitentUniqueID to make it clear it is not the same as The UniqueId Attribute as presented in spec.
The UniqueID attribute from the basicInformation value is now stored in our NVM3 config section. It is erased on factory reset. After factory reset, at init, we will generate a random unique id. A user can store a New UniqueID at runtime if he decides to with StoreUniqueId()
This code already exists so the only change in this PR on this topic is having the kConfigKey_UniqueId in the NVM3 config section which is erased on factory reset
Also …
=> [SL-UP] Split unique id and persistent unique

examples/lock-app/silabs/include/LockManager.h, examples/lock-app/silabs/src/LockManager.cpp
Cherry-pick fix for static variable retention in 917 doorlock app.
=> [SL-UP] 917 static variable retention fix

examples/lighting-app/silabs/data_model/lighting-thread-app.matter, examples/lighting-app/silabs/data_model/lighting-thread-app.zap, examples/lighting-app/silabs/data_model/lighting-wifi-app.matter, examples/lighting-app/silabs/data_model/lighting-wifi-app.zap
fixes [MATTER-4177](https://jira.silabs.com/browse/MATTER-4177)
coupleColorTempToLevelMinMireds attribute is a Manufacturer read-only attribute. It however much be set to a value that respect the following conditions
`ColorTempPhysicalMinMireds` <= `coupleColorTempToLevelMinMireds` <= `ColorTempPhysicalMaxMireds`
update the zap config for both wifi and thread so coupleColorTempToLevelMinMireds is equal to ColorTempPhysicalMinMireds
=> [SL-UP] Set coupleColorTempToLevelMinMireds at the same value than ColorTempPhysicalMinMireds

src/app/clusters/fan-control-server/fan-control-server.cpp, src/app/tests/suites/TestFanControl.yaml
This PR modifies the return value in the fan-cluster as per spec when NULL is written to percent-setting and speed-setting attributes.
=> [SL-UP] Updated return value when null is written as per spec

examples/all-clusters-app/all-clusters-common/src/fan-stub.cpp, src/app/clusters/fan-control-server/fan-control-server.cpp, src/app/clusters/fan-control-server/fan-control-server.h, src/app/util/util.cpp
Added an attribute access interface to modify the percent setting from changes on the speed setting ONLY when on client WRITE commands to the SpeedSetting attribute.
That way, we break the circular callback chain on percent changes that caused (With a MaxSpeed of 10):
Write PercentSetting: 25 -> Callback SpeedSetting -> 3 -> Callback PercentSetting: 30
=> [SL-UP] Circular callback fix

examples/lock-app/silabs/src/LockManager.cpp
Use of "Missing" Optional when pin length is 0 to prevent failure when no pin is used.
=> [SL-UP] No Pin Unlatch fix

src/platform/silabs/BLEManagerImpl.h, src/platform/silabs/efr32/BLEManagerImpl.cpp
Add logs for ble connection negotiations events. add a step to increase the ble connection timeout when it is under a preferred threshold.
=> [CSA-CP]ble connection parameters negociation

examples/platform/silabs/SoftwareFaultReports.cpp
Issue :
hitting 
`matter_sdk/examples/platform/silabs/SoftwareFaultReports.cpp:123:5: error: 'configASSERTNULL' was not declared in this scope; did you mean 'configASSERT'?` with sisdk 2024.12.0
the macro is defined in `FreeRTOSConfig.h `so use that include rather than 
`FreeRTOS.h`
=> [SL-UP] Change freertos include used to fix the macro not found

examples/platform/silabs/provision/ProvisionStorageDefault.cpp, src/platform/silabs/platformAbstraction/GsdkSpam.cpp, src/platform/silabs/platformAbstraction/SilabsPlatform.h, src/platform/silabs/platformAbstraction/SilabsPlatformBase.h, src/platform/silabs/platformAbstraction/WiseMcuSpam.cpp
Make abstractions of the different platforms' flash APIs in our SPAM. Use this abstraction for our provision storage to align code in a single structure
-     Updated the GsdkSpam for series 3 now that provisioning relies on it
-     Updated provisioning to use Silabs Platform Abstraction Manager
=> [CSA-CP]Provision SPAM

examples/platform/silabs/display/lcd.cpp
The LCD Display is not working on brd1019a yet. Do not crash the app if the display enable returns a failure. Log it and continue without the display.
=> [SL-TEMP] Don't assert app on display enable fail

examples/platform/silabs/MatterShell.cpp
Temp fix: add` include sl_status.h` because the following `sl_cmsis_os2_common.h` include sisdk header needs it and doesn't specify it
=> [SL-TEMP]fix missing sl status for cmsis os2 common

examples/platform/silabs/ldscripts/SiWx917-common.ld, third_party/silabs/SiWx917_sdk.gni, third_party/silabs/silabs_board.gni
Adds support for wiseconnect 3.4.0 in the GN build system. PR doesn't bring support for all boards.
Only the BRD4338A was tested.
=> [SL-UP] Add BRD4338A support for Wiseconnect 3.4 in GN

src/platform/silabs/wifi/SiWx/WifiInterface.cpp, src/platform/silabs/wifi/WifiInterfaceAbstraction.cpp, src/platform/silabs/wifi/WifiInterfaceAbstraction.h, src/platform/silabs/wifi/rs911x/WifiInterface.cpp
Wiseconnect wifi interface has a double abstraction :
- wfx_power_save
- wfx_rsi_power_save
Both function executed the same code. As such, removed the wfx_rsi_power_save function to only use the "standard" API.
=> [SL-UP] Delete unnecessary double abstraction for the wiseconnect power save functions

examples/platform/silabs/uart.cpp, examples/refrigerator-app/silabs/src/RefrigeratorUI.cpp, examples/thermostat/silabs/src/ThermostatUI.cpp, src/platform/silabs/multi-ota/OTACustomProcessor.cpp, src/platform/silabs/multi-ota/OTAFirmwareProcessor.cpp, src/platform/silabs/multi-ota/OTAMultiImageProcessorImpl.cpp
After the Wi-Fi abstraction refactor, the way to include certain files has changed since they moved from the examples directory to the platform directory. 
Some of the includes were not updated when the header was moved. PR updates the inclusion statement.
=> [SL-UP] Update spi-multiplex header inclusion

src/platform/silabs/SiWx917/SiWxPlatformInterface.h, src/platform/silabs/wifi/SiWx/WifiInterface.cpp, src/platform/silabs/wifi/WifiInterfaceAbstraction.h, src/platform/silabs/wifi/wf200/WifiInterface.cpp, src/platform/silabs/wifi/wf200/platform/efr_spi.c, src/platform/silabs/wifi/wf200/platform/sl_wfx_host.h
Some build combinations were not tested during the Wi-Fi interface refactor. This fixes some of the error that popped up when updating the components to integrate the Wi-Fi interface refactor.
=> [SL-UP] Fix Builds after Wi-Fi interface refactor

examples/platform/silabs/silabs_utils.h, src/platform/silabs/Logging.cpp, src/platform/silabs/Logging.h, src/platform/silabs/tracing/BUILD.gn, src/platform/silabs/tracing/SilabsTracing.cpp, src/platform/silabs/tracing/SilabsTracing.h, src/platform/tests/BUILD.gn, src/platform/tests/TestSilabsTracing.cpp
Initial Silabs Tracing object and unit tests. Next step: create silabs  matter tracing backend object and integrate in our Base App / main
Class diagram graciously provided by Copilot:
```mermaid
classDiagram
class SilabsTracer {
+static SilabsTracer& Instance()
+CHIP_ERROR Init()
+CHIP_ERROR StartWatermarksStorage(PersistentStorageDelegate* storage)
+void TimeTraceBegin(TimeTraceOperation aOperation)
+void TimeTraceEnd(TimeTraceOperation aOperation, CHIP_ERROR error = CHIP_NO_ERROR)
+void TimeTraceInstant(TimeTraceOperation aOperation, CHIP_ERROR error = CHIP_NO_ERROR)
+CHIP_ERROR OutputTimeTracker(const TimeTracker& tracker)
+CHIP_ERROR OutputWaterMark(TimeTraceOperation aOperation)
+CHIP_ERROR OutputAllWaterMarks()
+CHIP_ERROR TraceBufferFlushAll()
+CHIP_ERROR …
```
=> [SL-ONLY] Initial SilabsTracing object

examples/platform/silabs/BaseApplication.cpp, examples/platform/silabs/BaseApplication.h, src/platform/silabs/wifi/SiWx/WifiInterface.cpp, src/platform/silabs/wifi/WifiInterfaceAbstraction.cpp, src/platform/silabs/wifi/WifiInterfaceAbstraction.h, src/platform/silabs/wifi/icd/WifiSleepManager.cpp, src/platform/silabs/wifi/icd/WifiSleepManager.h, src/platform/silabs/wifi/rs911x/WifiInterface.cpp, third_party/silabs/SiWx917_sdk.gni
PR introduces the WifiSleepManager application callback class to enable application level logic to be injected into the WifiSleepManager to determine if in which low power mode can the Wi-Fi chip go to.
The structure of ApplicationCallback is to allow the WifiSleepManager to work with and without application logic being injected.
Validate that standard behavior still works if no callback is provided.
=> [SL-UP] Add application callback to allow the application to inject logic

src/app/InteractionModelEngine.cpp, src/app/InteractionModelEngine.h, src/app/SubscriptionsInfoProvider.h, src/app/icd/server/tests/TestICDManager.cpp, src/app/tests/TestInteractionModelEngine.cpp
PR adds a function that checks if a given fabric has at least 1 active subscriptions
This is necessary for the selective listening design to validate that for each fabric we have at least one subscription.
Unit tests
=> [SL-UP] Add fabric subscription check to the interaction model engine

src/platform/silabs/Logging.cpp, src/platform/silabs/Logging.h, src/platform/silabs/tracing/BUILD.gn, src/platform/silabs/tracing/SilabsTracing.cpp, src/platform/silabs/tracing/SilabsTracing.h, src/platform/tests/BUILD.gn, src/platform/tests/TestSilabsTracing.cpp
Cherry Picking the 2 commits introducing silabs trace. Wrongfully pushed on main instead of here.
=> [SL-ONLY] Silabs tracing cherry pick

src/lib/shell/Engine.cpp
When using the matter shell, a combination of:
backspace + enter or any special characters such as arrow keys would cause 
ExecCommand to be call with argc > 0, but argv == nulptr, which would crash the app.
This was tested using UART logs and screen command.
Added a nullptr check to prevent the crashes, in the longterm we might want to investigate how the filtering left us with argc > 0 in those cases.
=> [SL-UP] Bugfix/matter shell crash nullptr

src/platform/silabs/wifi/BUILD.gn, src/platform/silabs/wifi/WifiInterfaceAbstraction.h, src/platform/silabs/wifi/wf200/wf200.gni, src/platform/silabs/wifi/wfx_msgs.h, third_party/silabs/efr32_sdk.gni
When additional Wi-Fi platforms were added, WF200 defines and constructs were used for "non-silabs" platforms. During the Wi-Fi abstraction work, an effort was done to reduce the number of location where defines we set. 
Since the names were re-used with defines and the Si SDK defines thses names as typedef enums, there were build issue to flag that there could be values mismatchs.
PR moves the defines in a gatted section that is not used by the WF200 to avoid anything conflicting values.
Manuel tests to validates that WF200 can join a Wi-Fi network
=> [SL-UP] Remove WF200 define duplication to avoid value conflicts at runtime

LICENSE
PR changes the default license of the repo to the Silicon Labs msla unless the file defines a different header.
=> [SL-ONLY] Change repo license to the Silicon Labs msla

src/platform/silabs/Logging.cpp, src/platform/silabs/SiWx917/OTAImageProcessorImpl.cpp, src/platform/silabs/wifi/SiWx/WifiInterface.cpp, src/platform/silabs/wifi/WifiInterfaceAbstraction.cpp
- While adding wifi sleep manager component in extension , build and copy contents are failing for EFR and SoC platforms.
- Added CHIP_CONFIG_ENABLE_ICD_SERVER macro, wherever WifiSleepManager.h is included.
=> [SL-UP] Fix builds for sleep manager

src/app/ReadHandler.cpp
When the `OnSubscriptionTerminated` callback is called, the readhandler that is being destroyed is still marked as active even if the destructor has been called.
Due to this, if we want to check the state of the different subscription for the fabric, the readhandler that is being destroyed skews the results since it is marked as active.
PR removes the `ActiveSubscription` flag before calling the `OnSubscriptionTerminated` to avoid having false positives when checking for active subscriptions on the fabric afterwards. This also prevents the `OnSubscriptionTerminated` to be called twice if for some reason the destructor is called twice we shouldn't happen.
CI
=> [SL-UP] Remove the `ActiveSubscription` flag when the ReadHandler is being destroyed

examples/platform/silabs/sensors/AirQuality/AirQualitySensor.cpp
The latest update to drivers (third_party_hw_driver) has removed the file. Removing it from matter implementation as well.
=> [CSA-CP] removed unnecessary include (#36646)

src/platform/silabs/tracing/SilabsTracing.cpp
Removed reference to watermarks in output watermarks function to avoid compilation error when logs are disabled.
Converted static casts to to_underlying for enums.
=> [SL-ONLY]Bugfix/unused watermark attribute

src/platform/silabs/Logging.cpp, third_party/silabs/SiWx917_sdk.gni, third_party/silabs/efr32_sdk.gni
`SILABS_LOG_OUT_RTT ` 
Had not been added to any slcc files, it was therefore always set to true in Logging.cpp.
Since we are already using SILABS_LOG_OUT_UART as the conditionto toggle between both, I chose to completely remove 
SILABS_LOG_OUT_RTT as it was redundant. 
We could just as well update our logging components to add a define to SILABS_LOG_OUT_RTT's value in there though.
=> [SL-UP] Bugfix/silabs out rtt removal

third_party/silabs/SiWx917_sdk.gni, third_party/silabs/efr32_sdk.gni
Went back to if condition on gn args since :
In gn, `args=true `evaluates as a boolean, if `if(arg)` works
BUT
In preprocessor, `defines += "ARG=${arg}"` will yield :` #define ARG true` which is interpreted as a string, and doesn't work with the `#if !ARG` checks
=> [SL-ONLY] Bugfix/gn true to define true

examples/platform/silabs/MatterConfig.cpp, examples/platform/silabs/wifi/icd/ApplicationSleepManager.cpp
Due to a merge conflict, the init ended up being after the Server::Init which caused a crash upon boot up.
Re-ordered the init sequence
Manual tests
=> [SL-ONLY] Fix init sequence for the Application Sleep Manager

src/platform/silabs/wifi/SiWx/WifiInterface.cpp
- Added a join callback handler
- The unnecessary join events have been removed. The join event is posted multiple times, causing issues with the ecosystem during AP power cycles.
- The join retry limit has been removed. During the commissioning process, the MAX_JOIN_RETRIES_COUNT is set to 5, and this limit should be removed once commissioning is successful
Fixes https://jira.silabs.com/browse/MATTER-4379 and https://jira.silabs.com/browse/MATTER-4297
=> [SL-UP] Fix for access point power cycle rejoin issue with ecosystem

src/platform/silabs/SiWx917/OTAImageProcessorImpl.cpp
- Firmware upgrade status is modified in the latest WiSeConnect SDK and is updated in the Matter interface file.
Fixes https://jira.silabs.com/browse/MATTER-4276
=> [SL-UP] Updating the firmware upgrade status for SoC

examples/platform/silabs/MatterConfig.cpp, src/platform/silabs/PlatformManagerImpl.cpp, src/platform/silabs/wifi/SiWx/WifiInterface.cpp, src/platform/silabs/wifi/rs911x/platform/efx32_ncp_host.c
This PR fixes the init failure in 917NCP boards.
After integrating the matter_sdk code with the sl_net APIs, the init is failing because LWIP init is called twice for 917NCP. 
To resolve this, we have removed the LWIP init from PlatformManager and modified the init sequence to avoid errors while booting. But, with the recent SPI related changes, we are facing SPI_BUSY error. So, reverted the recent changes made in efx32_ncp_host.c file. With these changes, the init for 917NCP is passing.
=> [SL-UP] 917ncp init failure fix

examples/platform/silabs/BaseApplication.cpp, examples/platform/silabs/MatterConfig.cpp, examples/platform/silabs/main.cpp, src/platform/silabs/efr32/BUILD.gn, src/platform/silabs/efr32/OTAImageProcessorImpl.cpp, src/platform/silabs/tracing/BackendImpl.h, src/platform/silabs/tracing/SilabsTracing.h, src/platform/silabs/tracing/SilabsTracingMacros.h, src/platform/silabs/tracing/SilabsTracingTypes.h, src/tracing/silabs/include/matter/tracing/macros_impl.h
Wrapped calls to the tracer instance  methods with macros to reduce the amount of #if in the code by providing stubs when building without tracing like with MATTER_TRACE_...
=> [SL-ONLY] Silabs Tracing Macros

src/platform/silabs/efr32/BLEManagerImpl.cpp, src/platform/silabs/tracing/SilabsTracing.h
Deactivating the ChipLogDetail in `BleAdvTimeoutHandler` as it is causing a stack overflow.
Reducing the buffer size in SilabsTracing as the biggest message so far is around 100 bytes, letting us a buffer of 28bytes in the event of bigger trace names.
=> [SL-TEMP] Temp/ble adv timeout

examples/platform/silabs/FreeRTOSConfig.h, src/crypto/BUILD.gn, src/crypto/DefaultSessionKeystore.h, src/crypto/crypto.gni, src/crypto/tests/TestChipCryptoPAL.cpp, src/platform/silabs/efr32/CHIPCryptoPALPsaEfr32.cpp, src/platform/silabs/efr32/OTAImageProcessorImpl.cpp, src/platform/silabs/efr32/args.gni, src/platform/silabs/platformAbstraction/GsdkSpam.cpp
Cherry-pick of 
https://github.com/project-chip/connectedhomeip/commit/e98f2b239aae657a10043bad9aa61f4717d059be
https://github.com/project-chip/connectedhomeip/commit/a39c1787f083a829268055e333afd5cb73b0f971
The following changes are needed with sisdk 2024.12.0 most recent change to PSA crypto.
The two latest commits are actually sl-up
=> [SL-UP] Bring PSA crypto changes

examples/lighting-app/silabs/src/AppTask.cpp, examples/platform/silabs/shell/tracing/TracingShellCommands.cpp, src/platform/silabs/tracing/BUILD.gn, src/platform/silabs/tracing/SilabsTracing.cpp, src/platform/silabs/tracing/SilabsTracing.h, src/platform/silabs/tracing/SilabsTracingMacros.h, src/platform/tests/TestSilabsTracing.cpp
Added API for apps to register custom event to trace. Currently only supports instant trace, could be made to support begin and end if need be. 
This is integrated in Lighting and ZigbeeMatter Light apps. Tested on Series 3 and BRD4187C.
=> [SL-ONLY] Tracing App specific operation tracing

scripts/examples/gn_silabs_example.sh
Build script adjusted to support Crypto PAL PSA with PSA keystore for Wi-fi NCP only.
Tested with WF200 and Si917.
=> [SL-UP] Bugfix: PSA Crypto keystore for Wi-fi.

src/platform/silabs/wifi/SiWx/WifiInterface.cpp
Description of Problem:
The Wi-Fi connection attempt returns a timeout error (0x07). Following the timeout, subsequent Wi-Fi connection attempts during retry attempts always return either SL_STATUS_SI91X_SCAN_ISSUED_IN_ASSOCIATED_STATE or SL_STATUS_SI91X_COMMAND_GIVEN_IN_INVALID_STATE
Description of Solution:
Deactivate the network interface for the specific statuses mentioned above and enable the Wi-Fi connection on the next retry.
Fixes: https://jira.silabs.com/browse/MATTER-4198
=> [SL-UP] Deactivate the network interface for a specific Wi-Fi connection status to resolve the rejoin issue

examples/platform/silabs/wifi/icd/ApplicationSleepManager.cpp
**Problem**
With 917 NCP sleepy apps, if device is allowed to sleep at the time of commissioning window opened , it is failing with timeout at `sl_wifi_filter_broadcast` and returning there.
With 9116 sleepy apps, if  if device is allowed to sleep at the time of commissioning window opened , it is crashing at `rsi_bt_power_save_profile`.
**Temp-Fix**
Disabled sleep till wifi connection completed only for NCP devices.
=> [SL-TEMP] Temp-fix for 917 NCP sleep

src/platform/silabs/wifi/wiseconnect-abstraction/WiseconnectInterfaceAbstraction.cpp
Description of Problem:
The scan fails when both the SSID and scan callback are empty.
Description of Solution:
Enable scanning of all networks when the SSID is empty
Fixes: https://jira.silabs.com/browse/MATTER-4296
=> [SL-TEMP] Fix for the Amazon ecosystem's scan all networks issue

examples/platform/silabs/BaseApplication.cpp, examples/platform/silabs/wifi/icd/ApplicationSleepManager.cpp, src/platform/silabs/wifi/icd/WifiSleepManager.cpp, src/platform/silabs/wifi/icd/WifiSleepManager.h
When the commissioning complete event gets called for a succesful commissioning, the commissioning stopped callback doesn't get called. Due to this behavior, the `mIsCommissioningInProgress` member never gets reset which prevents us from ever going to LI based sleep in a standard run.
This was missed because it requires a clean run from commissioning to a subscribe attempt which apperently i missed.
PR adds a the PowerEvent data that can be passed to the WifiSleepManager to update the commissioning state.
Run a full sequence from start to finish without power cycling
=> [SL-UP] Fix Wi-Fi Sleep Manager commissioning progress check from clean boot

src/platform/silabs/wifi/SiWx/WifiInterface.cpp
Description of Problem:
The bg scan callback handler is not invoked during a connected Wi-Fi scan
Description of Solution:
Enable instant bg scanning to retrieve the network scan status.
Fixes: https://jira.silabs.com/browse/MATTER-4443
=> [SL-TEMP] Enable instant bg scanning to retrieve the network scan status

examples/platform/silabs/provision/ProvisionStorageCustom.cpp, examples/platform/silabs/provision/ProvisionStorageDefault.cpp, src/platform/silabs/efr32/CHIPCryptoPALPsaEfr32.cpp, src/platform/silabs/provision/ProvisionEncoder.h, src/platform/silabs/provision/ProvisionStorage.h
Now the provision.py script allows to set the size of the data buffer with the --buffer_size argument. This requires changes on the provision library.
Tested on BRD4187C.
=> [SL-UP] Provision: Dynamic buffer allocation

examples/platform/silabs/SilabsTestEventTriggerDelegate.cpp, examples/platform/silabs/provision/ProvisionStorageDefault.cpp, examples/platform/silabs/provision/ProvisionStorageFlash.cpp, src/platform/silabs/provision/ProvisionStorage.h
When the SDK check if the test event trigger is enabled, it checks if the test event trigger enableKey is equal to a zero Bytespan. If the enableKey matches, returns false that the feature is not enabled.
In the current implementation, if we fail to read the enable key, we immediatly return that the key does not match. If the key we are trying to match was the zero bytespan, this triggers the stack to think the feature is enabled since the platform enable key does not match the zero bytepspan which is incorrect.
The other issue was that we return that the enableKeys don't match if `!enableKeySpan.empty() `. When checking with the zero bytespan, this returns false immediatly without checking the platform enable key,
The PR changes the logic to always check if the data matches or not which, …
=> [SL-UP] Fix test event trigger enable validation

examples/light-switch-app/light-switch-common/light-switch-app.matter, examples/light-switch-app/light-switch-common/light-switch-app.zap, examples/light-switch-app/silabs/include/AppConfig.h, examples/light-switch-app/silabs/include/AppEvent.h, examples/light-switch-app/silabs/include/AppTask.h, examples/light-switch-app/silabs/include/BindingHandler.h, examples/light-switch-app/silabs/include/LightSwitchMgr.h, examples/light-switch-app/silabs/src/AppTask.cpp, examples/light-switch-app/silabs/src/BindingHandler.cpp, examples/light-switch-app/silabs/src/LightSwitchMgr.cpp, examples/light-switch-app/silabs/src/ShellCommands.cpp
This PR adds the dimmer-switch application by extending the existing light-switch application.
The zap file of light-switch app is modified by adding level-control-cluster client.The levelcontrol cluster can be controlled by sending commands from shell.
Button switch level control will be added in a follow up PR
**Tested:**
Tested locally with a lighting app device levelcontrol commands handled by the switch
=> [SL-UP]Adding the dimmer switch App

examples/platform/silabs/MatterConfig.cpp, src/platform/silabs/SiWx917/SiWxPlatformInterface.h, src/platform/silabs/platformAbstraction/WiseMcuSpam.cpp
This PR adds compilation fix with 917 SoC if button/LED components are disabled.
Added proper macros wherever button/led code is present.
Tested build locally with BRD4338A board.
=> [SL-UP]Fix SoC build if disable button and led components

examples/platform/silabs/wifi/icd/ApplicationSleepManager.cpp
With 917 NCP sleepy apps, if device is allowed to sleep before wifi connection ,it is failing to wakeup in si91x_req_wakeup().So delayed sleep tilll wifi connection. 
Added SLI_SI91X_MCU_INTERFACE macro before verifying the device can sleep, so that NCP will not enter power save mode till wifi-connection.
=> [SL-TEMP] Temp-fix for delay 917 NCP sleep till wifi-connection

src/platform/silabs/platformAbstraction/WiseMcuSpam.cpp
This PR adds linker error fix as led includes were not included in extern C
Added extern C for all LED includes.
Tested build locally with BRD4338A and BRD2605A board.
=> [SL-UP] Fix SoC linker error if led component added

examples/platform/silabs/shell/tracing/TracingShellCommands.cpp, src/platform/silabs/tracing/SilabsTracing.cpp, src/platform/silabs/tracing/SilabsTracing.h, src/platform/tests/TestSilabsTracing.cpp
Updated the formatting of the timestamps logs and added a check for empty buffer in tracing shell commands
=> [SL-ONLY] Bugfix/tracing log format

examples/platform/silabs/BaseApplication.cpp
re-enable channel steering for series 2. Update the ifdef condition to use `SL_CATALOG_RAIL_UTIL_IEEE802154_FAST_CHANNEL_SWITCHING_PRESENT` so it works independently with S2 or S3 and can be enabled/disable at will
=> [SL-ONLY] re-enable channel steering for series2. update the ifdef condition

src/platform/silabs/wifi/SiWx/WifiInterface.cpp, src/platform/silabs/wifi/wiseconnect-abstraction/WiseconnectInterfaceAbstraction.cpp
JIRA : [MATTER-4465](https://jira.silabs.com/browse/MATTER-4465)
Issue : While scanning network with a random SSID, the details of current network are being returned.
Fix : Fixed the string comparison code. These changes are picked up from the release_2.4-1.4 branch ([PR](https://github.com/SiliconLabsSoftware/matter_sdk/pull/81/files))
=> [SL-TEMP] Fixing scan networks code.

examples/platform/silabs/provision/ProvisionStorageFlash.cpp
Fixes MATTER-4490
Reverts change in logic of storage of private key to maintain backward compatibility
=> [SL-UP] Revert provision keystore to maintain backward compatibility

.github/workflows/silabs-update-csa.yaml
PR adds a cron job that will push the latest csa::master commit to the matter_sdk::csa branch.
The workflow succesfully ran on the test setup but there were no changes to process since the branch was already up to date.
We will need to validate tomorrow once this is merged that it worked
https://github.com/SiliconLabsSoftware/matter_sdk/actions/runs/12874387207/job/35893812596
=> [SL-ONLY] Add workflow to update the CSA branch daily

src/platform/silabs/wifi/SiWx/WifiInterface.cpp
Description:
The sl_net_up() API occasionally returns a timeout error (0x07) due to timeout is set to 5 seconds in wiseconnect.
From the next retry onward, the ScanCallback and sl_net_up() are returning SL_STATUS_SI91X_SCAN_ISSUED_IN_ASSOCIATED_STATE or SL_STATUS_SI91X_COMMAND_GIVEN_IN_INVALID_STATE.
Fix:
Timeout for the sl_wifi_connect() has been increased to 18 seconds similar to internal stack timeout in wiseconnect.
Testing:
Tested commissioning and power cycling locally with the 917 SoC.
=> [SL-TEMP] Remove sl_net_down workaround after calling the sl_net_up API

examples/light-switch-app/silabs/include/AppEvent.h, examples/light-switch-app/silabs/include/LightSwitchMgr.h, examples/light-switch-app/silabs/src/LightSwitchMgr.cpp
Description : This PR extends the button implementation in dimmer switch app by adding level control actions on button sequences. Below are the implementation details : 
Default Step direction - Up
Button1 short press - light toggle
Button1 long press - Level up/down as per direction
Button1 shortpress + Button0 shortpress - reverse the direction (down to up or up to down)
Button0 longpress - Factory reset
Testing : Tested the button sequences on SOC manually.
=> [SL-UP] Dimmer switch button implementation

.github/workflows/silabs-update-csa.yaml
For security reasons, the github token has no permissions to create or update workflows in a github action and there is no way to configure a workflow to give those permissions.
To do this, we had to create a PAT (Personnal access token) with the right permissions in the SiliconLabsSoftware org and use that token as a repository secret. The PAT can be re-used for multiple secrets. 
Manual test
=> [SL-ONLY] Change workflow token to use the PAT token with additionnal worklfow permissions

.github/workflows/silabs-open-csa-pr.yaml
PR adds a workflow that is triggered after the daily csa update to open a PR from csa to main with the latest CSA changes.
When testing the action I saw an issue with the CI was not being triggered on the PR opened by a Github Action but i think having the PAT token checkout and create the branch fixes the issue. With all the testing i can confirm a 100% this.
We will know tomorrow morning if the full flow works.
Check https://github.com/SiliconLabsSoftware/matter_sdk/pull/236
=> [SL-ONLY] Add workflow to open PR from csa to main after the csa update is completed

src/tracing/silabs/BUILD.gn
Add dependencies to fix ncp build when gen_tracing_buildconfig didn't get called in certain conditions.
Built the NCP that were crashing on CI.
=> [SL-UP] Tracing gen fix silabs_tracing

.github/silabs-builds-mg24.json
In the release branch, all builds for a board (thread + ncp) are built in the same directory so gn only detects a rebuild.
In certain cases, this can lead to failures being hidden because files don't get rebuilt with the correct defines / configurations.
See https://github.com/SiliconLabsSoftware/matter_sdk/actions/runs/12983608812/job/36205134063?pr=245 as example. A clean build of a NCP fails while this CI passes. This is due to the build not being "clean".
This isn't an issue for `main` or `csa` because the build script was changed to generate different paths for ncp builds.
CI
=> [SL-TEMP] Add clean argument to NCP builds to avoid hidden failures

examples/platform/silabs/FreeRTOSConfig.h
Raise the timer task to the highest priority. 
some slcc/slcp try to set configTIMER_TASK_PRIORITY for some stacks.
For example 
```
Timer RTOS task priority needs to be one more than SL_BT_RTOS_LINK_LAYER_TASK_PRIORITY
BT uses event flags that require the timer task to be a higher priority than all other RTOS tasks
```
In matter extension, we overwrite the generated freeRTOSConfig but our static config. This PR makes sure this prio is always set.
Manual commissioning and control tests.
=> [SL-UP] Raise TimerTask to the highest prio

examples/platform/silabs/BaseApplication.cpp
Inform the Zigbee stack that the device should not be considered factory-new once the matter commission is completed.
This will stop touch link broadcasts at reboots causing thread issues when concurrent channel listening is not available.
Matter zigbee sequential commission and reboot tests. SRP request at boot up works
=> [SL-ONLY] [CMP] ZLL not factory new

.github/workflows/silabs-open-csa-pr.yaml, .github/workflows/silabs-require-admin-action-check.yaml
PR adds a workflow that checks if the `sl-require-admin-action` label is present. If the label is present, the workflow fails to force admin action.
PR adds two jobs, one to check if the label is present and a second that checks if the label was removed.
The goal of this action is to force an admin validation on certain situations like the update of main from csa that requires a special merge strategy.
=> [SL-ONLY] Add require admin check workflow

third_party/silabs/silabs_board.gni
CI build is failing for 917 NCP boards as it has old matter_support pointer
Here, update matter_support changes to matter_sdk repo release branch
Verified build locally few apps and CI.
Verified commissioning and few commands on 917 NCP  board.
=> [CSA-CP]Bring matter_support changes to fix 917 NCP build fail in CI

.github/workflows/silabs-build-examples.yaml, .github/workflows/silabs-common-build.yaml
PR optimizes the CI behavior when building the sample apps. In changes two behavior in relation to concurrency and the matrix strategies
- We prevent concurrent builds for a same reference. In other words, we cancel on-going build steps if a new build is started.
- If one of the runs in the matrix fails, it will not stop the other strategies. This will allow us to leverage the CI to determine if there a multiple failures for a change without needing to re-run the CI
- Add workflow dispatch to be able to trigger the workflow manually
###
manual tests to validate the scenarios
=> [SL-ONLY] Optimize build behavior for the sample apps builder

src/platform/silabs/NetworkCommissioningWiFiDriver.cpp, src/platform/silabs/NetworkCommissioningWiFiDriver.h, src/platform/silabs/wifi/WifiInterfaceAbstraction.h, src/platform/silabs/wifi/wf200/WifiInterface.cpp, src/platform/silabs/wifi/wiseconnect-abstraction/WiseconnectInterfaceAbstraction.cpp
This PR fixes the Scan Networks issue mentioned in [MATTER-4650](https://jira.silabs.com/browse/MATTER-4650)
**Description of issue** : While scanning for a particular SSID(string), the size of the pointer to this string is taken as length of the string instead of the actual length.
**Description of Fix** : Replaced the pointer with Bytespan so that the length of the input SSID is calculated correctly.
=> [SL-TEMP] Modified scan networks code to use ByteSpan in place of pointer.

.github/silabs-builds-mg26.json, src/platform/silabs/tracing/BUILD.gn
Fixed tracing build and add tracing build option to CI to prevent future breakage
Built efr32 NCP apps, efr32 mg24 appps and efr32 mg26 apps with and without tracing enabled.
CI will tell if I enabled it properly.
=> [SL-ONLY] Tracing in CI

examples/light-switch-app/silabs/include/AppEvent.h, examples/light-switch-app/silabs/include/AppTask.h, examples/light-switch-app/silabs/include/BindingHandler.h, examples/light-switch-app/silabs/include/LightSwitchMgr.h, examples/light-switch-app/silabs/src/BindingHandler.cpp, examples/light-switch-app/silabs/src/LightSwitchMgr.cpp, examples/light-switch-app/silabs/src/ShellCommands.cpp
The files in the light-switch-app were not restyled causing the restyler to fail.
Broken from the PR
https://github.com/SiliconLabsSoftware/matter_sdk/pull/227
https://github.com/SiliconLabsSoftware/matter_sdk/pull/148
Restyler fixed can be seen in the CSA PR: https://github.com/project-chip/connectedhomeip/pull/37448 
[Cherry-picked the commits for this PR]
=> [SL-UP] Restyling the light switch app

src/platform/silabs/wifi/WifiInterfaceAbstraction.h, src/platform/silabs/wifi/wf200/WifiInterface.cpp
WF200 scan was sending RCPI value rather than the RSSI value. Fixing it so that the send value is RSSI
Formula for the RSSI
```
The following equation can be used to convert the RCPI value to corresponding dBm value.
[signal level in dBm] = (RCPI / 2) - 110
```
https://docs.silabs.com/wifi/wf200/rtos/latest/group-w-f-m-g-r-o-u-p-c-o-n-c-e-p-t-s
Tested on WF200
=> [SL-UP][WiFi] Fixing the rssi value for wf200

examples/platform/silabs/uart.cpp, src/platform/silabs/platformAbstraction/WiseMcuSpam.cpp
Description : This PR fixes the build for custom 917SOC boards
Issue : If a project is built for custom board, build errors are seen as a few board related header files are being included.
Fix : Wrapped such board specific headers with a macro.
Testing : With these changes, created a matter_extension for studio and checked the build for custom board in studio.
=> [SL-UP] Resolve build errors for custom board

src/platform/silabs/wifi/icd/WifiSleepManager.cpp, src/platform/silabs/wifi/icd/WifiSleepManager.h
PR upstreams the Selective Listening foundation of the WifiSleepManager.
CI to validate everything builds. PR has no functionnal changes.
=> [SL-ONLY] Add selective listening framework to WifiSleepManager

src/platform/silabs/efr32/CHIPCryptoPALPsaEfr32.cpp
* Cherry-pick from CSA master.
* Fixes #[35155](https://github.com/project-chip/connectedhomeip/issues/35155) in Silicon Labs devices.
* Supports `MBEDTLS_PSA_ASSUME_EXCLUSIVE_BUFFERS=0`.
* Successful commission and light toggle in BRD4187C (MG24), BRD4316A(MGM24), and BRD4118A (MG26).
=> [CSA-CP] PSA Crypto support for MBEDTLS_PSA_ASSUME_EXCLUSIVE_BUFFERS=0

examples/platform/silabs/shell/tracing/TracingShellCommands.cpp
The tracing enabled build on main branch was failing due to the change https://github.com/project-chip/connectedhomeip/pull/37660 is needed on the TracingShellCommands.cpp 
Testing via the CI build
=> [SL-ONLY] Fixing the tracing enabled build 

src/app/clusters/ota-requestor/DefaultOTARequestorStorage.cpp, src/app/clusters/ota-requestor/DefaultOTARequestorStorage.h, src/app/tests/TestDefaultOTARequestorStorage.cpp
Cherry pick https://github.com/project-chip/connectedhomeip/pull/37643 "Check if a duplicated provider is present before loading into RAM"
CI
=> [CSA-CP] Cherry pick the OTA fix (CSA PR #37643)

src/transport/raw/TCP.cpp, src/transport/raw/tests/TestTCP.cpp
* Fix Null Pointer Dereference in TCP Packet Handling
* Fix handle zero messageSize in TCP packet processing
* Add test for TCP MessageSize
* Modify test
* Restyled by clang-format
* Modify the position of an if statement
* Modify test
No specific test done on my end.
CI validate everything builds. This has been on main for a while now.
=> [CSA-CP] Fix Null Pointer Dereference in TCP Packet Handling

examples/air-quality-sensor-app/silabs/include/AppTask.h, examples/air-quality-sensor-app/silabs/src/AppTask.cpp, examples/chef/silabs/include/AppTask.h, examples/chef/silabs/src/AppTask.cpp, examples/energy-management-app/silabs/include/AppTask.h, examples/energy-management-app/silabs/src/AppTask.cpp, examples/light-switch-app/silabs/include/AppTask.h, examples/light-switch-app/silabs/src/AppTask.cpp, examples/lighting-app/silabs/include/AppTask.h, examples/lighting-app/silabs/src/AppTask.cpp, examples/lit-icd-app/silabs/include/AppTask.h, examples/lit-icd-app/silabs/src/AppTask.cpp, examples/lock-app/silabs/include/AppTask.h, examples/lock-app/silabs/src/AppTask.cpp, examples/platform/silabs/BaseApplication.cpp, examples/platform/silabs/BaseApplication.h, examples/pump-app/silabs/include/AppTask.h, examples/pump-app/silabs/src/AppTask.cpp, examples/refrigerator-app/silabs/include/AppTask.h, examples/refrigerator-app/silabs/src/AppTask.cpp, examples/smoke-co-alarm-app/silabs/include/AppTask.h, examples/smoke-co-alarm-app/silabs/src/AppTask.cpp, examples/thermostat/silabs/include/AppTask.h, examples/thermostat/silabs/src/AppTask.cpp, examples/window-app/silabs/include/AppTask.h, examples/window-app/silabs/src/AppTask.cpp
Cherry-pick of the changes in CSA + Traces for end of bootup.
---------
Build and ran on series2/3 917
=> [SL-ONLY] BaseApplication Init refactor

examples/air-quality-sensor-app/silabs/include/AppConfig.h, examples/air-quality-sensor-app/silabs/src/AppTask.cpp, examples/chef/silabs/include/AppConfig.h, examples/energy-management-app/silabs/include/AppConfig.h, examples/energy-management-app/silabs/src/AppTask.cpp, examples/light-switch-app/silabs/include/AppConfig.h, examples/light-switch-app/silabs/src/AppTask.cpp, examples/lighting-app/silabs/include/AppConfig.h, examples/lighting-app/silabs/src/AppTask.cpp, examples/lit-icd-app/silabs/include/AppConfig.h, examples/lit-icd-app/silabs/src/AppTask.cpp, examples/lock-app/silabs/include/AppConfig.h, examples/lock-app/silabs/src/AppTask.cpp, examples/platform/silabs/BaseApplication.cpp, examples/pump-app/silabs/include/AppConfig.h, examples/pump-app/silabs/src/AppTask.cpp, examples/refrigerator-app/silabs/include/AppConfig.h, examples/refrigerator-app/silabs/src/AppTask.cpp, examples/smoke-co-alarm-app/silabs/include/AppConfig.h, examples/smoke-co-alarm-app/silabs/src/AppTask.cpp, examples/thermostat/silabs/include/AppConfig.h, examples/thermostat/silabs/src/AppTask.cpp, examples/window-app/silabs/include/AppConfig.h, examples/window-app/silabs/src/AppTask.cpp
Moved all LCD init into BaseApplication to reduce code duplication.
Added the recent BaseApp change in the dishwasher app.
Standardized BLE_ADV naming with app display naming.
Compile & Flash app with app name on display such as: light app, dishwasher app, etc.
=> [CSA-CP] BaseApplication common LCD Init

examples/platform/silabs/cmp/sl-matter-attribute-storage.cpp, examples/platform/silabs/cmp/sl-matter-attribute-storage.h
This PR adds a silabs internal api to sync Zigbee datamodel to matter's on zb attribute write.
`sli_matter_af_write_attribute` is called from the zigbee stack when the generated multiprotocol mapping is available.
note: file naming conventions doesn't correspond ours/matter's but was decided with the sisdk convention
Commission the Zigbee Matter CMP Light to matter and zigbee network. Update on-off, level-control, color-control attributes for either network and confirm the update is also done one the counterpart datamodel.
=> [SL-ONLY]Add cmp datamodel sync api

src/platform/silabs/wifi/SiWx/WifiInterface.cpp
**Cherry Pick of** https://github.com/project-chip/connectedhomeip/pull/38011
Added GPIO_BASED_HANDSHAKE Wifi configurations for 917 NCP. This bit is enables GPIO-based handshake for low power mode and here ULP GPIO 1 is for wake-up indication. If this bit is not enabled before wifi connection , then sl_si91x_req_wakeup  will be failed in SPI re-initialization whenever host tries to wakeup 917 NCP module for Tx/Rx events.
Tested sleepy app commissioning on 917 NCP and commands
=> [CSA-CP]  Added 917 NCP wakeup source config

examples/platform/silabs/provision/BUILD.gn
Devices fail to commission when not provisioned when build with GN
`CHIP_DEVICE_CONFIG_ENABLE_EXAMPLE_CREDENTIALS` was replaced by `SL_MATTER_ENABLE_EXAMPLE_CREDENTIALS` with new matter_support structure within the gn build config. However within matter 1.4 ProvisionStorageDefault.cpp and ProvisionStorageFlash.cpp the #ifdef to enable de example fallback have not being changed. Additionally Matter_Extension 2.5-1.4 and 2.6-1.4 still define `CHIP_DEVICE_CONFIG_ENABLE_EXAMPLE_CREDENTIALS`
To minimize the change and upgrade rules with in matter 1.4 release, Re-add CHIP_DEVICE_CONFIG_ENABLE_EXAMPLE_CREDENTIALS in GN build for the provisionStorageXXX sources.
SL_MATTER_ENABLE_EXAMPLE_CREDENTIALS is already present in matter 1.5 and 1 single upgrade rule can be done for matter extension …
=> [SL-TEMP] Fix commissioning with test credentials

src/platform/silabs/NetworkCommissioningWiFiDriver.cpp
Fixes [MATTER-4789](https://jira.silabs.com/browse/MATTER-4789)
Issue : When the length of connected SSID is 32, observing NetworkID as False during read network. While returning the connected network details, error is being returned if the length of SSID is <32, but it should be <=32 since the maximum allowed length of SSID is 32. Added this small fix in length comparision.
Tested locally by commissioning to a network with SSID of length 32, the read networks command is successful.
=> [SL-TEMP] Fixed length comparision while returning the details of current network

src/platform/silabs/wifi/rs911x/rsi_wlan_config.h, third_party/silabs/silabs_board.gni
RS9116 sleep/wakeups are not working due to incorrect configurations of RSI_TCP_IP_FEATURE_BIT_MAP and RSI_FEATURE_BIT_MAP. Added rs9116 configurations in rsi_wlan_config.h
Validated commissioning and commands on EFR + RS9116 board.
Verified power cycle and factory reset.
CSA PR: https://github.com/project-chip/connectedhomeip/pull/38078
=> [CSA-CP] Fixed RS9116 sleep issue

examples/lock-app/silabs/build_for_wifi_args.gni, examples/platform/silabs/wifi/icd/ApplicationSleepManager.cpp, examples/platform/silabs/wifi/icd/ApplicationSleepManager.h, examples/platform/silabs/wifi/icd/vendor-handlers/AppleKeychainHandler.h, examples/platform/silabs/wifi/icd/vendor-handlers/BUILD.gn, examples/platform/silabs/wifi/icd/vendor-handlers/VendorHandler.h, examples/platform/silabs/wifi/icd/vendor-handlers/VendorHandlerFactory.h, examples/platform/silabs/wifi/icd/vendor-handlers/tests/BUILD.gn, examples/platform/silabs/wifi/icd/vendor-handlers/tests/TestAppleKeychainHandler.cpp, examples/platform/silabs/wifi/icd/vendor-handlers/tests/TestVendorHandler.cpp, examples/platform/silabs/wifi/icd/vendor-handlers/tests/TestVendorHandlerFactory.cpp, src/platform/silabs/CHIPDevicePlatformConfig.h, src/platform/silabs/tests/BUILD.gn, third_party/silabs/SiWx917_sdk.gni
The goal of the PR is to refactor the Vendor exception processing to make it easier to expand overtime. Instead of having hardcoded logic in ApplicationSleepManager.
The logic used is through the CRTP to avoid using dynamic allocation. The current implementation is resolved at compile time.
- `VendorHandler` : interface class that defines the structure of the handlers
- `VendorHandlerFactory` : interface that calls all the handler defined in the ApplicationSleepManager
- `AppleKeychainHandler` : Exception handler for the apple that uses two fabrics with a single active one
Some configuration changes weren't cherry-pick to the main branch since the PR in question was marked SL-UP but they were changed to SL-ONLY during the development process.
- Manual tests with the BRD4338A with …
=> [SL-ONLY] Refactor Selective Listening vendor exception handling

examples/window-app/silabs/include/WindowManager.h, examples/window-app/silabs/src/AppTask.cpp, examples/window-app/silabs/src/WindowManager.cpp
The window app QR code doesn't exists hence once commissioning is done the LCD display shows, no image found.
Adding the window app LCD display as a custom UI so the LCD is updated based on the UI.
JIRA: https://jira.silabs.com/browse/MATTER-4792 (image attached)
Tested getting the window screen after commissioning
**Note:** Noticed that there is no cycle screen present, hence the permanent fix would be adding and verifying all the btn changes and update display. On btn click as well LCD update is not happening as expected.
Will be creating a ticket to fix this.
=> [SL-UP] Adding the Custom UI for the window app

examples/platform/silabs/BaseApplication.cpp
https://jira.silabs.com/browse/MATTER-4885 
With some Thread apps (most often seen in ICDs) the BaseApplication::OnPlatformEvent() does not get registered in time to receive the DeviceEventType::kThreadConnectivityChange event when the device joins the Thread network. As a result the OTA Requestor does not get initialized. 
Add another OTA Requestor initialization call from DeviceEventType::kDnssdInitialized event handling. The  OTA Requestor initialization is idempotent and is safe to call multiple times (i.e. in cases when we catch both the Thread and DNS-SD handling). 
Verified that OTA Requestor init is invoked even if  DeviceEventType::kThreadConnectivityChange event is missed. Verified that NotifyUpdateApplied command is sent out in the OTA Update scenario.
=> [SL-TEMP] Init the OTA Requestor based on the DNS-SD event

examples/platform/silabs/BaseApplication.cpp
Merge 2.5 into 2.6. It can be directly fast-forwarded. It brings only 1 pr
just ci
=> [SL-TEMP] Init the OTA Requestor based on the DNS-SD event (#399)

examples/platform/silabs/FreeRTOSConfig.h, src/test_driver/efr32/include/FreeRTOSConfig.h
The new FreeRTOS kernel relies on a file that is not supported in Sisdk.
Disabling configUSE_NEWLIB_REENTRANT avoids including that file.
No impact was measured on device performance after removing this config.
Compile, flash, commission, toggle
=> [SL-UP]Removed configUSE_NEWLIB_REENTRANT 

examples/platform/silabs/wifi/icd/vendor-handlers/AppleKeychainHandler.h, examples/platform/silabs/wifi/icd/vendor-handlers/tests/TestAppleKeychainHandler.cpp
While doing multi-admin test cases, I noticed while using the Google Home app on my iphone that the Appley Keychain fabric was being added to the device even if the operating fabric was not Apple. This behavior was preventing the device from entering Listen based sleep because the exception handler tried to find an Apple fabric to validate that it had an activate subscription while the fabric was not present on the device.
The PR modifies the exception handler to verify if we find an Apple fabric. If the Apple fabric is absent but we have an Apple Keychain fabric, this means that the operationnal fabric is not Apple's and the exception handler should not prevent the device from going to sleep.
- Updated the unit-tests to reflect the new behavior
- The multi-admin test case that allowed me …
=> [SL-ONLY] Fix Apple Keychain fabric edge-cases for multi-admin

src/platform/silabs/DiagnosticDataProviderImpl.cpp, src/platform/silabs/platformAbstraction/WiseMcuSpam.cpp
- As memory_manager support is not there in wifi_sdk, returning `CHIP_ERROR_UNSUPPORTED_CHIP_FEATURE` while reading software diagnostics attributes.
- Removed setting the highest priority for SVCall_IRQn  as sl_device_init_nvic() was used and  causing the hardfault issue.Now `sl_si91x_device_init_nvic()` is used hence it is not required.
Testing
Verified software diagnostics attributes returning '0' after commission with 917SoC board.
=> [SL-TEMP] Removed software diagnostics support for 917 SoC

.github/workflows/zap_regeneration.yaml, .github/workflows/zap_templates.yaml
In release_2.6-1.4, the zap_template_generation GitHub action is using a deprecated Ubuntu version for building. 
Was fixed in CSA to use ubuntu-latest. This PR cherry picks it. 
We are only seeing this issue today, as this is the cut-off date for it , according to https://github.com/actions/runner-images/issues/11101
Picks up CSA PR: https://github.com/project-chip/connectedhomeip/pull/37870
=> [CSA-CP] : Stop using old ubuntu version (#37870)

examples/lighting-app/silabs/src/AppTask.cpp, examples/platform/silabs/SoftwareFaultReports.cpp, src/platform/silabs/SilabsConfig.cpp, src/platform/silabs/SilabsConfig.h, src/platform/silabs/SilabsConfigCTM.cpp
Cleanup of SilabsConfig and implementation of common token manager API, had to keep some nvm3 calls due to lack of API for those.
Compile -> Provision -> Flash -> Commission -> Toggle
Compared tokens fetched with old and new API, compatibility seems to work.
=> [SL-UP] Feature/common token manager

examples/platform/silabs/BaseApplication.cpp
Zigbee data model state for nvm attributes are stored in Tokens. We were not actively clearing those on our factory reset sequence.
This PR added the call for it.
Commission CMP app on Rainier. toggle light on. Factory reset the device with pb0. Confirm light is off after reboot and init
=> [SL-ONLY] Add factory reset call for zigbee

examples/platform/silabs/wifi/icd/ApplicationSleepManager.cpp
ApplicationSleepManager is verifying whether 917 TA module is ready to go sleep, before going to power save mode.
As the RS9116 sleep had issues, #ifdef  **SLI_SI917** were added in the ApplicationSleepManager.cpp to so that RS9116 module will not enter into powersave mode . These ifdefs can be removed now as the RS9116 sleep issue got resolved.
Verified commissioning ,commands and factory reset with EFR BRD4187C + RS9116. 
After power cycle device is not able to connect to AP as ssid and passkey values are incorrect while reading from NVM3.
Jira ticket for the issue - https://jira.silabs.com/browse/MATTER-4930
=> [SL-ONLY] Removed define guards in ApplicationSleepManager

.github/workflows/silabs-open-csa-pr.yaml, .github/workflows/silabs-update-csa.yaml
In the initial implementations of the automation workflows used a PAT (personal access token) associated to my github account for the missing permissions the `GITHUB_TOKEN` available by default did not have. The issue with the PAT is that it executed actions with my github handle at moments where it would be preferable to have a "bot" do them.
By replacing the PAT with a github app, the permissions are associated with the github app and not to my personnal account. This removes the depency on my to keep everything going and simplifies some of the automation since we don't need to work around the lacking permissions of the github token.
PR replaces the PAT where it is used in the matter_sdk by the github app token. The changes to use the Github App is only done where the github token does …
=> [SL-ONLY] Update csa update workflows to use github app

.github/workflows/silabs-require-admin-action-check.yaml
Exit call being used was javascript code in a bash context. PR replaces with the correct exit function.
See CI failure - doesn't crash anymore.
Failure case : https://github.com/SiliconLabsSoftware/matter_sdk/actions/runs/14764010735/job/41451227702
=> [SL-ONLY] Replace javascript exit call with bash exit

.github/workflows/silabs-open-csa-pr.yaml, .github/workflows/silabs-require-admin-action-check.yaml, .github/workflows/silabs-update-csa.yaml
PR aims to clean up silabs specific workflows to remove unnecessary permissions and re-enforce string matching for the admin check action
- Remove unnecessary permissions given to the GitHub token.
- Make the string check much more stringent to avoid any shenanigans if a user were to comment the required string with additional text.
- Mask the generated token to avoid it being printed.
CI and automation once merge - should not have any impacts.
=> [SL-ONLY] Reduce overall permissions and add input checks

src/inet/tests/TestInetEndPoint.cpp
Description:
- TestInetEndPoint was not hermetic, it required at least one network interface connected to a link and up.
- There was a comment before to skip tests if the link was not up, but it was not actually skipping the test. This made it fail for me when working offline and trying to run unit tests.
Testing done:
- Test passes with and without link up.
Unit test ci
=> [CSA-CP]Fix TestInetEndPoint to pass even when computer is offline (#38015)

src/lwip/freertos/sys_arch.c
Cherry Pick of https://github.com/project-chip/connectedhomeip/pull/38757
Adds fix for integer overflow in LWIP function which causes timer to not work post 70mins.
Manually tested using logs of LWIP timers with CSA PR
=> [CSA-CP] Adds fix for integer overflow in TicksToMS function

src/platform/silabs/tracing/SilabsTracing.cpp, src/platform/tests/TestSilabsTracing.cpp
#Fixes Matter-4543 by switching the time reference to the RAIL timer instead of FreeRTOS SysTick
Tested with a MG24, we can now see the Init and bootup time compared to the previous implementation which returned 0.
App used : CMP app on MG24, build with SLC.
=> [SL-ONLY] Matter-4543 update tracing time source

examples/platform/silabs/MatterConfig.cpp, examples/platform/silabs/main.cpp, src/platform/silabs/platformAbstraction/GsdkSpam.cpp
Add support for sl_main for EFR32/SIMG301 platform inits in place of the deprecated sl_system.
This change only takes place with slc. 
sl_main does not apply to 917.
GN cannot use it either until it supports sisdk 2025.6
remove SL_POWER_MANAGER_EM1 workaround as it is not needed anymore with 2025.6
Build mg26 and 917 lighting app with gn
Build mg24, simg301 and 917 lighting app with SLC. 
Manually tested commissioning and light control with the MG24
=> [SL-UP]Support sl_main and remove SL_POWER_MANAGER_EM1 workwaround

.github/workflows/silabs-zap-failure-regen.yaml
With the automated updates of main from CSA, it often happens where the zap generation of silabs specific apps needs to be regenerated. This forces a manual step on the automation process that needs to be executed by a developer.
To elevate this requirement in case of failure, the PR aims to add workflow that is triggered if the zap generation validation fails on the automation PRs. The newly added workflow regenerates the templates and pushes the commit to the automation branch.
- https://github.com/SiliconLabsSoftware/matter_sdk/actions/runs/15030429196/job/42241439938
- https://github.com/SiliconLabsSoftware/matter_sdk/pull/455
=> [SL-ONLY] Add automation to regen zap in case of failure on automation PRs

src/platform/silabs/SilabsConfig.cpp, src/platform/silabs/SilabsConfig.h, src/platform/silabs/SilabsConfigCTM.cpp
Added the logic to get the size from the string when not provided in WriteConfigValueStr
Build, flash, commission, toggle
=> [SL-UP] Sizeless WriteConfigValueStr fix

src/access/AccessControl.cpp, src/access/AccessControl.h, src/app/MessageDef/AttributeDataIB.h, src/app/WriteClient.cpp, src/app/WriteClient.h, src/app/clusters/access-control-server/access-control-server.cpp, src/app/tests/TestWriteInteraction.cpp, src/app/tests/suites/TestAccessControlCluster.yaml, src/app/tests/suites/certification/Test_TC_ACL_2_3.yaml, src/app/tests/suites/certification/Test_TC_ACL_2_4.yaml, src/app/tests/suites/certification/Test_TC_ACL_2_5.yaml, src/app/tests/suites/certification/Test_TC_ACL_2_6.yaml, src/app/tests/suites/certification/Test_TC_ACL_2_8.yaml, src/controller/tests/TestWriteChunking.cpp
MATTER-4856
Cherry-pick from csa repo
* Modifying how ACL Attribute is written: making it use a non-empty initial ReplaceAll list
* removing Test modifications on ACL Extensions
* adding reference to issue in TODO comment
* integrating comments
* integrating comments
* Revert "removing Test modifications on ACL Extensions"
This reverts commit 055af80d6c71e40ddeef081b6046263bc06ef141.
* Clarifying AttributeDataIB Checkpoint
* adding Valid CAT values
* Integrating comments
* Add comments clarifying AttributeDataIB rollback
* Integrating comments again
* change method order
* integrating new comments
* revert change to IM Error Code return from AccessControl cluster
* changing constants use to reserveBuffer for TLV writing
* Integrating more Boris Comments
* removing state related to …
=> [CSA-CP][ACL][WriteClient] Encoding non-empty ReplaceAll when writing to AccessControl Cluster

.github/silabs-builds-mg24.json, .github/silabs-builds-mg26.json, src/platform/silabs/efr32/BLEManagerImpl.cpp
Build fails with unused variable error when apps are built without logs.
Fix: Remove the usage of the local variable
Build app with log disable/release
=> [SL-UP] Fix/unused var in ble manager

third_party/silabs/SiWx917_sdk.gni
Manually building application with the change in the `matter_provision` repo on a later commit, meanwhile facing issue on `release_2.6-1.4`, 
```
ERROR: Cannot install protobuf and protobuf~=5.28.2 because these package versions have conflicting dependencies.
```
=> [SL-UP] Add wrap config include path to siwx917_sdk template

examples/platform/silabs/provision/ProvisionStorageDefault.cpp, examples/platform/silabs/provision/ProvisionStorageFlash.cpp, src/platform/silabs/multi-ota/OTACustomProcessor.cpp, src/platform/silabs/multi-ota/OTAFactoryDataProcessor.cpp, src/platform/silabs/multi-ota/OTAFirmwareProcessor.h, src/platform/silabs/multi-ota/OTATlvProcessor.cpp, src/platform/silabs/multi-ota/OTATlvProcessor.h, src/platform/silabs/multi-ota/OtaTlvEncryptionKey.h, src/platform/silabs/multi-ota/OtaTlvEncryptionKeyMbed.cpp, src/platform/silabs/multi-ota/OtaTlvEncryptionKeyPSA.cpp, src/platform/silabs/multi-ota/SiWx917/OTAWiFiFirmwareProcessor.h
- Fixed build of multi-ota when custom TLV is enabled and encryption enabled on 917 SoC
- Clean up
Verified multi-ota with 917 SoC for plain image as well as encryption enabled and working.
OTA file creation commands : `./third_party/matter_sdk/scripts/tools/silabs/ota/ota_multi_image_tool.py create -v 0xFFF1 -p 0x8005 -vn 2 -vs "2.0" -da sha256 --app-input-file soc_combined.rps combined.ota`
` ./third_party/matter_sdk/scripts/tools/silabs/ota/ota_multi_image_tool.py create -v 0xFFF1 -p 0x8005 -vn 2 -vs "2.0" -da sha256 --app-input-file soc_combined_enc.rps combined_enc.ota --enc_enable --input_ota_key 0287421a84c97308a4d47371fe462e25`
=> [SL-UP] Adds fix and clean up of multi-ota

src/platform/silabs/wifi/SiWx/WifiInterface.cpp
NETGEAR access point working poorly with 917 SoC.
- Include WiFi aggregation only for 917 NCP modes.
Tested with NETGEAR access point as issue is seen on NETGEAR.
=> [SL-UP] Refactor WiFi configuration for aggregation feature

examples/platform/silabs/BaseApplication.cpp, examples/platform/silabs/MatterConfig.cpp, src/platform/silabs/platformAbstraction/GsdkSpam.cpp
With SiSDK 2025.6.0 the Matter projects use the sl_main component and the corresponding scheduling initialization logic. The projects upgraded to SiSDK 2025.6.0 (Matter 2.6.0) use the sl_system and the corresponding logic (project upgrades do not modify main.cpp). The current PR selects the sl_system logic to be followed in the upgraded projects. The upgraded projects are detected by the presence of the SL_CATALOG_CUSTOM_MAIN_PRESENT: the sl_main_custom_main component is new in 2025.6.0 and is added to the project by the SiSDK upgrade rule. See https://github.com/SiliconLabsSoftware/matter_sdk/pull/450 for context. 
Unrelated to the above, add [[maybe_unused]] to a stub function to prevent possible compile warnings. 
Verified that Matter/Thread projects upgraded from 2.4.5-1.4 to …
=> [SL-UP] Use sl_system logic in upgraded projects

src/platform/silabs/multi-ota/OtaTlvEncryptionKeyMbed.cpp
The build for 917 SoC is failing when multi ota is enabled.
https://jira.silabs.com/browse/MATTER-5096
Local build with mult-ota enabled.
=> [SL-UP] Removing the unused variable when multi ota is enabled

examples/light-switch-app/silabs/src/AppTask.cpp, examples/window-app/silabs/src/WindowManager.cpp
Init failure is seen in window-app and light-switch app due to timer-stop failure after factory-reset.
In this [PR](https://github.com/SiliconLabsSoftware/matter_sdk/pull/486), the error handling has been modified. In timer::Stop() API in window-app and light-switch app, if Timer::Stop() function doesn't return osOk(success code), the error is being logged and the app will be aborted. Earlier, Timer::Stop() function is being aborted only if it returns osError (error code -1).
After factory-reset, btn0 release event is being posted. This event will call Timer::Stop() function, which is failing with error code -3(osErrorResource //Resource not available.).
Below is the flow of timer actions on button press and release : 
When btn0 is pressed - a new timer will be started as follows : 
> …
=> [SL-UP] Init fix for timer failure

src/platform/silabs/efr32/BLEChannel.h
Added the missing =0 in BLEChannel methods
This would cause linking issue when building with optimization O0.
Built with O0, note the O0 code doesn't fit on our part so it couldn't be tested further.
=> [SL-UP] BLEChannel added missing pure virtual

examples/platform/silabs/shell/ble/BLEShellCommands.cpp, src/platform/silabs/BLEManagerImpl.h, src/platform/silabs/efr32/BLEChannel.h, src/platform/silabs/efr32/BLEChannelImpl.cpp, src/platform/silabs/efr32/BLEChannelImpl.h, src/platform/silabs/efr32/BLEManagerImpl.cpp
**Summary of Commit `4d157d5c115e15fb923531f3086dcc57e12a6f02`:**
Clean up BLE side channel read/write logic, remove magic numbers, and add support for "indicate" and "notify" operations.
- Added new shell commands for BLE side channel:
- `Notify`: Triggers a notify event on the TX characteristic.
- `Indicate`: Triggers an indicate event on the TX characteristic.
- Registered these commands in the shell command table.
- Added `SideChannelNotify()` and `SideChannelIndicate()` methods to trigger notifications and indications on the side channel TX characteristic.
- Updated GATT-related methods to use new naming and handle types (`uint16_t` instead of `uint8_t` for characteristic handles).
- Refactored characteristic handling:
- Introduced a `Characteristic` struct with handle and buffer.
- …
=> [SL-UP] BLE Side channel indicate/notify support

src/platform/silabs/multi-ota/OTAFactoryDataProcessor.cpp
This PR fixing the multi-ota factory  data update on 917 SoC.
https://jira.silabs.com/browse/MATTER-5068
Tested on 917 SoC with the following steps:
- Provision the 917 SoC board.
- Build the ota file using sample certification files. 
```
./ota_image_tool.py create -v 0xFFF1 -p 0x8005 -vn 2 -vs "2.0" -da sha256  --factory-data --dac_cert provision/samples/light/3/dac_cert.der --dac_key provision/samples/light/3/dac_key.der --pai_cert provision/samples/light/3/pai_cert.der --cert_declaration provision/samples/light/3/cd.bin matter-silabs-lighting-example.ota
./chip-ota-provider-app -f  matter-silabs-lighting-example.ota
./chip-tool pairing onnetwork 1 20202021
./chip-tool accesscontrol write acl '[{"fabricIndex": 1, "privilege": 5, "authMode": 2, "subjects": [112233], "targets": null}, …
```
=> [SL-UP] Fixing multi-ota factorydata update for 917 SoC

examples/zigbee-matter-light/silabs/src/AppTask.cpp
The zigbee app was broken after the last CSA update. 
Fixing the headers path.
Due to the change https://github.com/project-chip/connectedhomeip/pull/39693
Build locally
=> [SL-ONLY] Fixing the zigbee app with latest update

examples/platform/silabs/SoftwareFaultReports.cpp, examples/platform/silabs/uart.cpp, src/platform/silabs/Logging.cpp
Added a uart flush to force a uart output without relying on the uart task when we hit a fault, added handlers for faults other than hardfault to get logs.
Simulated faults with a wrongly addressed pointer by dereferencing it, observed logs would be generated.
Note: The equivalent PR is also up on CSA.
=> [CSA-CP]Fault Logging Fix

scripts/tools/silabs/ota/crypto_utils.py, src/platform/silabs/multi-ota/OTAFirmwareProcessor.cpp, src/platform/silabs/multi-ota/OTAMultiImageProcessorImpl.cpp, src/platform/silabs/multi-ota/OTATlvProcessor.cpp, src/platform/silabs/multi-ota/OTATlvProcessor.h, src/platform/silabs/multi-ota/SiWx917/OTAWiFiFirmwareProcessor.cpp
The payload of the application/firmware image may not be properly aligned, but for AES encryption the payload needs to be `block_size` aligned, in this case that is `16`. Currently, we are using a naive `0xFF` padding, but that assumes that the payload will not end with `0xFF` which is risky. Hence replacing the naive padding logic with PKCS7 standardized logic.
Since the padding is done on the file and not on the block, this means the last block of the file will have the padding data, hence the last block of the file needs to be identified and padding needs to be removed from that to get back the original file.
=> [SL-UP] Adds support for PKCS7 padding in OTA flow

examples/platform/silabs/MatterConfig.cpp
This reverts commit a0845c83a447675f8dd160ed5b5277ac7ec9942e.
With the latest SISDK. This temp fix isn't needed anymore. The thread stack does not set an EM1 power req during init anymore.
n/a
Power consumption was validated without this SLC-FIX during release 2.6-1.4 cycle.
=> Revert "[SL-TEMP] Bugfix temporary em req removal (#43)"

.github/silabs-builds-mg24.json, third_party/silabs/efr32_sdk.gni
This requires matter_support pr: https://github.com/SiliconLabsSoftware/matter_support/pull/140 to be merged beforehand.
Modified build script to use gatt client libraries with the side-channel and the stubs otherwise.
=> [SL-TEMP] BLE Side-Channel  gatt client lib

src/platform/silabs/ConfigurationManagerImpl.cpp
Added a check on the values set at the OTA reset to determine if the underlying reboot cause was a software update.
https://jira.silabs.com/browse/MATTER-5177
Simulating a software update and printing the value at boot, showed expected values.
code readable:
-   [x] PR size is short
-   [x] Try to avoid "squashing" and "force-update" in commit history
-   [x] CI time didn't increase
See: [Pull Request …
=> [SL-UP] Software Update BootReason

examples/air-quality-sensor-app/air-quality-sensor-common/air-quality-sensor-app.matter, examples/air-quality-sensor-app/air-quality-sensor-common/air-quality-sensor-app.zap, examples/closure-app/closure-common/closure-app.matter, examples/closure-app/closure-common/closure-app.zap, examples/dishwasher-app/silabs/data_model/dishwasher-thread-app.matter, examples/dishwasher-app/silabs/data_model/dishwasher-thread-app.zap, examples/dishwasher-app/silabs/data_model/dishwasher-wifi-app.matter, examples/dishwasher-app/silabs/data_model/dishwasher-wifi-app.zap, examples/light-switch-app/light-switch-common/icd-lit-light-switch-app.matter, examples/light-switch-app/light-switch-common/icd-lit-light-switch-app.zap, examples/light-switch-app/light-switch-common/light-switch-app.matter, examples/light-switch-app/light-switch-common/light-switch-app.zap, examples/lighting-app/silabs/data_model/lighting-thread-app.matter, examples/lighting-app/silabs/data_model/lighting-thread-app.zap, examples/lighting-app/silabs/data_model/lighting-wifi-app.matter, examples/lighting-app/silabs/data_model/lighting-wifi-app.zap, examples/lock-app/silabs/data_model/lock-app.matter, examples/lock-app/silabs/data_model/lock-app.zap, examples/pump-app/silabs/data_model/pump-thread-app.matter, examples/pump-app/silabs/data_model/pump-thread-app.zap, examples/pump-app/silabs/data_model/pump-wifi-app.matter, examples/pump-app/silabs/data_model/pump-wifi-app.zap, examples/refrigerator-app/silabs/data_model/refrigerator-thread-app.matter, examples/refrigerator-app/silabs/data_model/refrigerator-thread-app.zap, examples/refrigerator-app/silabs/data_model/refrigerator-wifi-app.matter, examples/refrigerator-app/silabs/data_model/refrigerator-wifi-app.zap, examples/smoke-co-alarm-app/smoke-co-alarm-common/smoke-co-alarm-app.matter, examples/smoke-co-alarm-app/smoke-co-alarm-common/smoke-co-alarm-app.zap, examples/window-app/common/window-app.matter, examples/window-app/common/window-app.zap
This is a cherry-pick PR from CSA to update the default value in zap files for General Commissioning cluster.
CSA PR : https://github.com/project-chip/connectedhomeip/pull/40530
MATTER-5267
Built lighting-app for 917SOC board, commissioned and verified that cluster revision value is '2' by sending a read command.
./chip-tool generalcommissioning read cluster-revision 1 1
Output : ClusterRevision: 2
code readable:
-   [x] PR size …
=> [CSA-CP] Update cluster revision default value in General commissioning cluster

examples/refrigerator-app/silabs/include/EventHandlerLibShell.h, examples/refrigerator-app/silabs/include/RefrigeratorManager.h, examples/refrigerator-app/silabs/include/refrigerator-and-temperature-controlled-cabinet-mode.h, examples/refrigerator-app/silabs/src/EventHandlerLibShell.cpp, examples/refrigerator-app/silabs/src/RefrigeratorManager.cpp, examples/refrigerator-app/silabs/src/ZclCallbacks.cpp
This is a cherry-pick PR from CSA to add support for suppressing an alarm using shell command to address a failing test case (TC_REFALM-2_3).
CSA PR : https://github.com/project-chip/connectedhomeip/pull/40463
[MATTER-4492](https://jira.silabs.com/browse/MATTER-4492)
Device commissioned successfully.
Executed the shell command to suppress the refrigerator alarm.
Verified that both the alarm state and mask values update correctly, reflecting the suppression.
code readable:
[_“When in Rome…”_](https://project-chip.github.io/connectedhomeip-doc/style/CO …
=> [CSA-CP] Add support to suppress alarm using shell

src/platform/silabs/wifi/SiWx/WifiInterface.cpp
The issue is seen when `sl_net_up` has successfully joined the WiFi access point, and is in the process of IP negotiation, specially SLAAC. During this SLAAC DAD process if the WiFi disconnects and the application receives a `JoinFailure` callback, the application has no way to abort the process. The `sl_net_up` in the IP negotiation process is not sensitive to the lower layer connection. This will cause `sl_net_up` to report a `SL_STATUS_OK` even when things are not.
A proper fix from Wiseconnect SDK is expected in 4.0.0, hence raising a SL-TEMP.
Currently tried to fix the condition by checking the state of the device before proceeding with the status obtained from `sl_net_up`.
Done locally.
code readable:
- …
=> [SL-TEMP] Adds fix to sl_net_up handling to prevent duplicate join failure event

examples/refrigerator-app/silabs/src/EventHandlerLibShell.cpp
Refrigerator app shell build was failing with the v1.4.2 merge
Cherry-pick of the PR:
https://github.com/project-chip/connectedhomeip/pull/40197
Run and build with shell enabled with the 917SoC
=> [CSA-CP] Matter Shell fixing for the refrigerator devices

src/messaging/ReliableMessageMgr.cpp
Attempt to clarify the RMP exhausted retry failure log so it doesn't look like 1 extra Retransmission was sent.
For example, it would log:
<<1 [E:10711r S:25050 M:158128181] (S) Msg Retransmission to 1:000000004E192DE4
<<2 [E:10711r S:25050 M:158128181] (S) Msg Retransmission to 1:000000004E192DE4
<<3 [E:10711r S:25050 M:158128181] (S) Msg Retransmission to 1:000000004E192DE4
<<4 [E:10711r S:25050 M:158128181] (S) Msg Retransmission to 1:000000004E192DE4
<<5 [E:10711r S:25050 M:158128181] (S) Msg Retransmission to 1:000000004E192DE4 failure (max retries:4)
Giving the impression to some Users that a 5th retransmission was sent when the max retries configured was 4.
The change is to remove the extra count(5) and try to clarify the error message.
<<_ [E:10711r S:25050 M:158128181] (S) Msg …
=> [CSA-CP]Clarify the RMP attempt limit reached failure log

src/platform/silabs/wifi/SiWx/WifiInterfaceImpl.cpp
The default fallback option for security when scan failed, is supposed to be WPA3 transition when WPA3 support is enabled in the device.
This primarily will cause a problem when the scan on the MATTER application fails, and we use the default options for maximum coverage.
NOTE: This was missed during the refactor efforts.
N/A
code readable:
-   [ ] PR title is
-   [ ] Apply the
-   [ ] PR size is short
-   [ ] Try to avoid "squashing" and "force-update" in commit …
=> [SL-UP] Update WiFi security setting to use WPA3 transition mode as fallback

src/platform/silabs/wifi/SiWx/WifiInterfaceImpl.cpp, src/platform/silabs/wifi/icd/PowerSaveInterface.h, src/platform/silabs/wifi/icd/WifiSleepManager.cpp
The application was not maintaining the state of the power profile of the device; thus it was invoking power profiles unnecessarily. This PR brings in a variable to maintain the current state of the device and only invoke low-level API in case the power profile changes.
[MATTER-5404](https://jira.silabs.com/browse/MATTER-5404)
Testing done using the SOC and verified by adding debug statements in the code flow.
```
[00:00:00.006][info  ][DL] Starting scheduler
[00:00:00.005][info  ][DL] ==================================================
[00:00:00.009][info  ][DL] SL-Lock starting
[00:00:00.011][info  ][DL] ==================================================
[00:00:00.012][info  ][DL] Init CHIP Stack
[00:00:02.353][detail][DL] [PWR] Configuring power save: 0 with listen interval: 0 …
```
=> [SL-ONLY] Adds check for power state change for invoking low-level power save APIs

src/app/icd/server/ICDManager.cpp, src/platform/silabs/ConnectivityManagerImpl_WIFI.cpp
In ICD applications for the 917SoC, we observed misleading error logs originating from the `SetPollingInterval` API, despite the application functioning correctly. These logs stem from the `_SetPollingInterval` method in the Connectivity Manager, which currently returns `CHIP_ERROR_NOT_IMPLEMENTED` as the feature is not yet supported. The upper layer interprets this as a failure, resulting in unnecessary error messages.
This PR addresses the issue by:
- Adding a conditional check for `CHIP_ERROR_NOT_IMPLEMENTED` in the upper layer to suppress misleading logs.
- Ensuring that the absence of implementation does not trigger failure handling.
- Adding a TODO comment to revisit and update the error handling logic once the polling interval feature is fully implemented.
This cleanup improves log …
=> [SL-UP] Suppress misleading error logs from unimplemented SetPollingInterval API

src/platform/silabs/CHIPPlatformConfig.h
PR adds the `CHIP_CONFIG_MRP_RETRY_INTERVAL_SENDER_BOOST` configuration to the silabs platform configuration.
It sets the default configuration to 2.5 seconds.
The goal of adding this configuration is to reduce the overall speed of retries for Wi-Fi application. The sender boost configuration adds the configuration to all retries to slow them down. In other words, if the calculated retry is 1s, the device will retry 3.5s later (1s + sender boost). 
Currently, retries for wi-fi devices with ecosystems are in the milliseconds. In home environements, it is impossible to round trips sub 1s. The 2.5 second configuration was decided based on emperic tests in the office and in my home network to be the highest lowest value were there were no unecessary retries due to network latency.
For thread, …
=> [SL-UP] Add silabs sender boost configuration to platform configuration

examples/platform/silabs/MatterConfig.cpp
With pr https://github.com/SiliconLabsSoftware/matter_sdk/pull/603
We now run the Migration at an earlier stage on EFR32 platforms.
For WiFi ncp builds, the Matter MemoryInit was not done yet which led to an assert and crash when allocating memory during a migration function.
In this PR Set mbedtls platforms callbacks and call MemoryInit earlier for wifi platforms jsut before the Platform Init which will possibly run Migrations for EFR32.
For EFR32. The same `mbedtls_platform_set_calloc_free `and `MemoryInit()` is done even ealier when we call sl_ot_create_instance during sl_system inits.
Lastly, for 917 SoC NVM3 can only be used once TA is sync with M4 therefore all the migrations are done a bit later after `InitWiFiStack`. Doing the chip::Platform::MemoryInit() doesn't do any harm …
=> [SL-UP] Fix init crash with WiFi-ncp platforms. 

src/platform/silabs/KeyValueStoreManagerImpl.cpp
On Series 3, nvm3 secure API can sometimes use up to 1100 bytes on the stack.
`KvsKeyMapCleanupTask` is a task that runs once at init and can execute multiple nvm3 read or write successively.
In a rare occurrence, on power cycling of the device, a Stack overflow of this task occurred.
This PR increases the KvsKeyMapCleanupTask stack size to 1536 bytes, a 1024-byte increase. While this is targeted at series 3 use case, we can safely apply it to all our platforms and avoid conditional/configuration logic.
The stack of the task is dynamically allocated, and the task is deleted once the cleanup is completed, freeing the 1536 bytes allocated.
MATTER-5377
MATTER-5397
Tested by building and running the init sequence on Series 2, Series 3 and 917 soc and verifying the task stack usage watermarks …
=> [SL-UP] Increase KvsKeyMapCleanup stack to address overflow risk

src/platform/silabs/NetworkCommissioningWiFiDriver.cpp, src/platform/silabs/wifi/WifiInterface.cpp, src/platform/silabs/wifi/WifiInterface.h
The retry timer is not getting reset on a successful connection after a retry, thus consecutive retry attempts are set as per the existing timer value.
NOJIRA
This was tested by rebooting the access point.
code readable:
-   [ ] Apply the
-   [ ] PR size is short
-   [ ] Try to avoid "squashing" and "force-update" in commit history
-   [ ] CI time didn't increase
See: [Pull Request Guidelines](https://project-chip.github.io/connectedhomeip-doc/cont …
=> [SL-UP] Reset retry interval on WiFi connection notification

.github/workflows/restyled.yml, scripts/helpers/restyle-diff.sh, scripts/helpers/restyle_merge.sh
PR updates the restyler tooling from CSA for it to work in the context of matter_sdk where the default branch is main and not master and that devs can be working directly on the matter_sdk or a fork.
The logic that is beeing added is detecting what kind of setup is being used and choosing the correct remote based on the git configuration.
PR also gives extra permissions to restyled action to be able to open PRs when a dev with write access pushes a PR that requires restyle - https://github.com/SiliconLabsSoftware/matter_sdk/pull/648
The downside of this we can't avoid the codeowners guetting a notification due to the limited features of github in this regard. We can see if this becomes a problem and remove PRs as a whole.
**restyle-diff changes**
1. If origin is this repo, main repo setup …
=> [SL-ONLY] Update restyle scripts to work with matter_sdk structure
